### ISSUE TITLE
Add Unit Testing for CAM

### ISSUE THREAD

**Issue by slahav** [CurriculumAssociates/createjs-accessibility#11]
It would be great if we could add unit testing to CAM that will be:
1. integrated into CI/CD.
2. produce a coverage.
3. run for every opened PR.

**Comment by drosenberg123** [comment]
Unit test framework added in [PR #60](https://github.com/CurriculumAssociates/createjs-accessibility/pull/60)
Coverage reporting added in [PR #83](https://github.com/CurriculumAssociates/createjs-accessibility/pull/83)
